### ISSUE TITLE
Add launcher app icon 

### ISSUE THREAD

**Issue by oliverj96** [oliverj96/katy_trail_app#37]
All that needs to be done here is to add the app launcher icon that we received from Dr. Smith into the assets/image folder.  

There should be an iOS version and Android version.

**Comment by fredoderazin** [comment]
This is the icon Dr. Smith is having his designers work on, right?

**Comment by oliverj96** [comment]
Yes

**Comment by 20annageorge** [comment]
Yes, but this issue is just for importing the needed packages/ adding assets that will be used to add the icon and testing an icon to make sure it will show up on ios and android. So, once his designers give us the icon, all we will have to do is pop it into the assets/images folder and everything’s done.
